# Generated by Django 5.1 on 2024-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='ingredients',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='method',
            field=models.TextField(max_length=2000),
        ),
    ]
