# Generated by Django 5.1 on 2024-08-20 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0002_alter_receipe_ingredients_alter_receipe_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='receipe',
            name='description',
            field=models.TextField(default='blank=True, null=True', max_length=100),
            preserve_default=False,
        ),
    ]
